### ISSUE TITLE
[BUG] InteractingScp330 return the wrong CandyKindID

### ISSUE THREAD

**Issue by Antoniofo** [ExMod-Team/EXILED#118]
**Describe the bug**
When the event is fire the CandyKindID is not the same as the one reveived by the player

**To Reproduce**
1. Put a log into the event about the ev.Candy
2. Go to SCP330
3. Take a candy'
4. See that the log is not the same as the candy in the inventory

**Expected behavior**
The candy Logged should be the same as the candy reveived

**Server logs**
Not necessary as there is not exeption thrown

**EXILED Version ("latest" is not a version):**
Exiled 8.12.2

**Results of `pluginmanager show` command in console:**
                                
                                 [2024-09-25 21:31:32.234 +02:00] Total number of plugins: 6
                                 Enabled plugins: 6
                                 Disabled plugins: 0

                                 Exiled.Events:
                                        - Author: Exiled Official
                                        - Version: 8.12.2.0
                                        - Required Exiled Version: 8.12.2.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 Exiled.CustomRoles:
                                        - Author: Exiled Official
                                        - Version: 8.12.2.0
                                        - Required Exiled Version: 8.12.2.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Candy Utilities:
                                        - Author: @misfiy
                                        - Version: 1.0.8
                                        - Required Exiled Version: 8.12.2
                                        - Prefix: CandyUtils
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 8.12.2.0
                                        - Required Exiled Version: 8.12.2.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Official
                                        - Version: 8.12.2.0
                                        - Required Exiled Version: 8.12.2.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Official
                                        - Version: 8.12.2.0
                                        - Required Exiled Version: 8.12.2.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium

**Additional context**
 -

**Comment by VALERA771** [comment]
Fix commited on dev branch and icluded in Halloween update. Thanks for reporting and helping to make exiled better!
