### ISSUE TITLE
[BUG] DiscordIntegrationBot displays number of players incorrectly

### ISSUE THREAD

**Issue by Tamago4a** [ExMod-Team/EXILED#120]
https://github.com/Exiled-Team/DiscordIntegration/issues/151
![image](https://github.com/user-attachments/assets/955e1642-c769-4560-b7f2-252225f18d2c)

**Describe the bug:**
Discord bot displays player count incorrectly. It counts NPCs when it shouldn't.

**To Reproduce:**
1. Add plugin and configure bot
2. Create NPC on server
3. Make sure the number of players displayed is incorrect

**EXILED Version:**
8.11.0

**Comment by VALERA771** [comment]
NPC are added into this dictionary and iirc it's intendend feature

**Comment by Tamago4a** [comment]
> NPC are added into this dictionary and iirc it's intendend feature

Then who is right? In any case, this discord bot displays the number of players incorrectly.

**Comment by iamalexrouse** [comment]
> > NPC are added into this dictionary and iirc it's intendend feature
> 
> Then who is right? In any case, this discord bot displays the number of players incorrectly.

Hi!

If you want to filter out NPCs in `Player.List`, you can use `Player.List.Where(x => !x.IsNPC)`.
This filters out NPCs from the player list since the Dictionary, by default gets every "player", including NPCs.

Thanks,
Alex.

**Comment by Tamago4a** [comment]
> > > NPC are added into this dictionary and iirc it's intendend feature
> > 
> > 
> > Then who is right? In any case, this discord bot displays the number of players incorrectly.
> 
> Hi!
> 
> If you want to filter out NPCs in `Player.List`, you can use `Player.List.Where(x => !x.IsNPC)`. This filters out NPCs from the player list since the Dictionary, by default gets every "player", including NPCs.
> 
> Thanks, Alex.

I don't want to filter any player lists. I'm trying to figure out whose fault it is that Joker119's discord bot is showing the wrong number of players.

**Comment by Tamago4a** [comment]
Is anyone going to do anything about this?

**Comment by iamalexrouse** [comment]
I don't think so, as far as I know, DiscordIntegration uses an outdated version of Exiled, which means fixes like non-NPCs would not be possible on the exiled version DiscordIntergration is built for.

**Comment by louis1706** [comment]
Intended

**Comment by Tamago4a** [comment]
I thought it would be easier for me to create a new bot without code overload than to try to revive this. Because it compiles, but does not run. It's some kind of spaghetti code and I don't understand how to figure it out. You can close the PR. Happy New Year to everyone.
