### ISSUE TITLE
[BUG] cant make npcs

### ISSUE THREAD

**Issue by 6not9you** [ExMod-Team/EXILED#171]
using dev dummies
cant spawn them/manipulate them in admin panel
![image](https://github.com/user-attachments/assets/7b6d83f6-a8bd-4e02-8506-2771095b8b51)
![image](https://github.com/user-attachments/assets/56d4e80e-bcce-49e6-9286-854103d3f199)
![image](https://github.com/user-attachments/assets/4dc479a7-c065-4375-afc1-a090013affdc)

**Comment by skyfr0676** [comment]
because `npc.ReferenceHub.authManager.InstanceMod` is on `Dedicated Server` and not on `Verified` state. you can manually patch RAPlayerList to show players.
personnaly i made this for npcs
![image](https://github.com/user-attachments/assets/8d3c1e62-46be-41ac-a668-4479e2f75c6f)

**Comment by SrLicht** [comment]
> because `npc.ReferenceHub.authManager.InstanceMod` is on `Dedicated Server` and not on `Verified` state. you can manually patch RAPlayerList to show players. personnaly i made this for npcs ![image](https://private-user-images.githubusercontent.com/99112969/385921631-8d3c1e62-46be-41ac-a668-4479e2f75c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1Mjg2MDgsIm5iZiI6MTczMTUyODMwOCwicGF0aCI6Ii85OTExMjk2OS8zODU5MjE2MzEtOGQzYzFlNjItNDZiZS00MWFjLWE2NjgtNDQ3OWUyZjc1YzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDIwMDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZGMxODUxN2IwZDZkOWU5MDFmNmI4YWUwMGQ2MmFlMzY0MWE3MGEzODNjNTdiNWJlZGYxYjY3MzQ3OGM5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M-QiauFIBKyiO-R28mB6PXejXUoCnF1iAb2VzpUeN48)

I think you are breaking the VSR by assigning NPCs in the Verified instance, that is exclusive to real players and if you are not careful you can inflate the number of connected players on your server which can lead to breaking the VSR. That is why NPCs are assigned in NoVerified or DedicatedServer.

**Comment by skyfr0676** [comment]
> > because `npc.ReferenceHub.authManager.InstanceMod` is on `Dedicated Server` and not on `Verified` state. you can manually patch RAPlayerList to show players. personnaly i made this for npcs ![image](https://private-user-images.githubusercontent.com/99112969/385921631-8d3c1e62-46be-41ac-a668-4479e2f75c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1Mjg2MDgsIm5iZiI6MTczMTUyODMwOCwicGF0aCI6Ii85OTExMjk2OS8zODU5MjE2MzEtOGQzYzFlNjItNDZiZS00MWFjLWE2NjgtNDQ3OWUyZjc1YzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDIwMDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZGMxODUxN2IwZDZkOWU5MDFmNmI4YWUwMGQ2MmFlMzY0MWE3MGEzODNjNTdiNWJlZGYxYjY3MzQ3OGM5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M-QiauFIBKyiO-R28mB6PXejXUoCnF1iAb2VzpUeN48)
> 
> I think you are breaking the VSR by assigning NPCs in the Verified instance, that is exclusive to real players and if you are not careful you can inflate the number of connected players on your server which can lead to breaking the VSR. That is why NPCs are assigned in NoVerified or DedicatedServer.

on my server NPCS is not verified and not shown as a player (i have 3 npcs always active but it's actually say 0/30 on the server list), this is just a patch of RA player list

**Comment by louis1706** [comment]
Fixed on new release
