### ISSUE TITLE
[BUG] Guns have no initial ammo after respawning

### ISSUE THREAD

**Issue by Qidan475** [ExMod-Team/EXILED#204]
**Describe the bug**
After player respawn, all guns in inventory have 0 ammo initially

**EXILED Version ("latest" is not a version):**
9.0.0-alpha.1

**Additional context**
When giving guns manually via RA it works fine

![image](https://github.com/user-attachments/assets/ddb14b9c-e046-47f9-bcf4-70c2e77f6d2e)

**Comment by louis1706** [comment]
It's now fixed
