### ISSUE TITLE
RestartingRound event

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [ExMod-Team/EXILED#221]
HarmonyLib.HarmonyException: Patching exception in method static System.Void RoundRestarting.RoundRestart::InitiateRoundRestart() ---> System.TypeLoadException: Could not resolve type with token 01000070 from typeref (expected class 'MapGeneration.DoorSpawnpoint' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')

**Comment by Misaka-ZeroTwo** [comment]
Deployed a temp fix. Waiting for NW to fix PluginAPI.

**Comment by VALERA771** [comment]
NW released a pre version with fixes for 14.0. Didn't test it but I suppose that this issue is fixed

**Comment by Misaka-ZeroTwo** [comment]
still need to revert the patch back once NW actually deploys it to the public beta branch.
