### ISSUE TITLE
Scp3114FriendlyFireFix

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [ExMod-Team/EXILED#224]

**Comment by Misaka-ZeroTwo** [comment]
Removed this patch for now, requires testing to see if the issue still exists.

**Comment by louis1706** [comment]
![image](https://github.com/user-attachments/assets/84063b0a-ddf7-4188-8bf0-92c4743bda3b)
i don't see change on the code

**Comment by louis1706** [comment]
I did fixed it
