### ISSUE TITLE
[BUG]DOESN'T WORK EXILED

### ISSUE THREAD

**Issue by Mattarellot2** [ExMod-Team/EXILED#315]
![image](https://github.com/user-attachments/assets/dd22ef30-491e-471d-b261-cd5aa0624905)
My error

**Comment by VALERA771** [comment]
Check if you have updated EXILED and it's been installed correctly. You can also try to reinstall it manually (usually this helps)

**Comment by tgbhy** [comment]
Did you installed the PluginAPI.dll provided by NW for server hosters ?

**Comment by louis1706** [comment]
Invalide installation
