### ISSUE TITLE
[BUG] If event is cancelled on NWAPI, Exiled's won't run

### ISSUE THREAD

**Issue by JayXTQ** [ExMod-Team/EXILED#99]
**Describe the bug**

**To Reproduce**
1. Cancel an event via NWAPI
2. Try logging out info on that same event
3. See no log

OR

1. Have CedMod on your server
2. Run Exiled event LocalReport
3. See it doesn't run

**Expected behavior**
Event should always run.

**EXILED Version ("latest" is not a version):**

8.11.0

**Comment by VALERA771** [comment]
Seems to be correct for `ReportingCheater` event

**Comment by VALERA771** [comment]
Merged on dev and will be in release soon. Thanks for reporting. We appreciate your help
